// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commissions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkReferralCommissionExists = `-- name: CheckReferralCommissionExists :one
SELECT EXISTS(
    SELECT 1 FROM commissions
    WHERE user_id = $1 AND user_type = 'MEMBER' AND product_id IS NULL AND referral_code = $2
)::boolean
`

type CheckReferralCommissionExistsParams struct {
	UserID       uuid.NullUUID  `json:"user_id"`
	ReferralCode sql.NullString `json:"referral_code"`
}

func (q *Queries) CheckReferralCommissionExists(ctx context.Context, arg CheckReferralCommissionExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkReferralCommissionExists, arg.UserID, arg.ReferralCode)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createCommission = `-- name: CreateCommission :one
INSERT INTO commissions (
    user_id, product_id, amount, status, user_type, referral_code
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, product_id, amount, status, created_at, user_type, user_id, referral_code
`

type CreateCommissionParams struct {
	UserID       uuid.NullUUID      `json:"user_id"`
	ProductID    uuid.NullUUID      `json:"product_id"`
	Amount       int64              `json:"amount"`
	Status       string             `json:"status"`
	UserType     CommissionUserType `json:"user_type"`
	ReferralCode sql.NullString     `json:"referral_code"`
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error) {
	row := q.db.QueryRowContext(ctx, createCommission,
		arg.UserID,
		arg.ProductID,
		arg.Amount,
		arg.Status,
		arg.UserType,
		arg.ReferralCode,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UserType,
		&i.UserID,
		&i.ReferralCode,
	)
	return i, err
}

const getCommissionLeaderboard = `-- name: GetCommissionLeaderboard :many
SELECT 
    c.user_id,
    c.user_type,
    COALESCE(m.name, r.name, 'User')::text as user_name,
    SUM(c.amount)::bigint as total_amount
FROM commissions c
LEFT JOIN members m ON c.user_id = m.id AND c.user_type = 'MEMBER'
LEFT JOIN resellers r ON c.user_id = r.id AND c.user_type = 'RESELLER'
GROUP BY c.user_id, c.user_type, m.name, r.name
ORDER BY total_amount DESC
LIMIT 10
`

type GetCommissionLeaderboardRow struct {
	UserID      uuid.NullUUID      `json:"user_id"`
	UserType    CommissionUserType `json:"user_type"`
	UserName    string             `json:"user_name"`
	TotalAmount int64              `json:"total_amount"`
}

func (q *Queries) GetCommissionLeaderboard(ctx context.Context) ([]GetCommissionLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommissionLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommissionLeaderboardRow
	for rows.Next() {
		var i GetCommissionLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserType,
			&i.UserName,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommissionsByUser = `-- name: GetCommissionsByUser :many
SELECT id, product_id, amount, status, created_at, user_type, user_id, referral_code FROM commissions
WHERE user_id = $1 AND user_type = $2
ORDER BY created_at DESC
`

type GetCommissionsByUserParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	UserType CommissionUserType `json:"user_type"`
}

func (q *Queries) GetCommissionsByUser(ctx context.Context, arg GetCommissionsByUserParams) ([]Commission, error) {
	rows, err := q.db.QueryContext(ctx, getCommissionsByUser, arg.UserID, arg.UserType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commission
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UserType,
			&i.UserID,
			&i.ReferralCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCommission = `-- name: GetPendingCommission :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE user_id = $1 AND user_type = $2 AND status = 'PENDING'
`

type GetPendingCommissionParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	UserType CommissionUserType `json:"user_type"`
}

func (q *Queries) GetPendingCommission(ctx context.Context, arg GetPendingCommissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingCommission, arg.UserID, arg.UserType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalCommission = `-- name: GetTotalCommission :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE user_id = $1 AND user_type = $2 AND status = 'PAID'
`

type GetTotalCommissionParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	UserType CommissionUserType `json:"user_type"`
}

func (q *Queries) GetTotalCommission(ctx context.Context, arg GetTotalCommissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCommission, arg.UserID, arg.UserType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalCommissionAll = `-- name: GetTotalCommissionAll :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE user_id = $1 AND user_type = $2
`

type GetTotalCommissionAllParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	UserType CommissionUserType `json:"user_type"`
}

func (q *Queries) GetTotalCommissionAll(ctx context.Context, arg GetTotalCommissionAllParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCommissionAll, arg.UserID, arg.UserType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserCommissions = `-- name: GetUserCommissions :many
SELECT 
    c.id, c.product_id, c.amount, c.status, c.created_at, c.user_type, c.user_id, c.referral_code, 
    p.title as product_title,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM commissions c
JOIN products p ON c.product_id = p.id
WHERE c.user_id = $1 AND c.user_type = $2
ORDER BY c.created_at DESC
`

type GetUserCommissionsParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	UserType CommissionUserType `json:"user_type"`
}

type GetUserCommissionsRow struct {
	ID           uuid.UUID          `json:"id"`
	ProductID    uuid.NullUUID      `json:"product_id"`
	Amount       int64              `json:"amount"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
	UserType     CommissionUserType `json:"user_type"`
	UserID       uuid.NullUUID      `json:"user_id"`
	ReferralCode sql.NullString     `json:"referral_code"`
	ProductTitle string             `json:"product_title"`
	ThumbnailUrl string             `json:"thumbnail_url"`
}

func (q *Queries) GetUserCommissions(ctx context.Context, arg GetUserCommissionsParams) ([]GetUserCommissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCommissions, arg.UserID, arg.UserType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCommissionsRow
	for rows.Next() {
		var i GetUserCommissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UserType,
			&i.UserID,
			&i.ReferralCode,
			&i.ProductTitle,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
