// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commissions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCommission = `-- name: CreateCommission :one
INSERT INTO commissions (
    reseller_id, product_id, amount, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, reseller_id, product_id, amount, status, created_at
`

type CreateCommissionParams struct {
	ResellerID uuid.UUID `json:"reseller_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Amount     int64     `json:"amount"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error) {
	row := q.db.QueryRowContext(ctx, createCommission,
		arg.ResellerID,
		arg.ProductID,
		arg.Amount,
		arg.Status,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.ResellerID,
		&i.ProductID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCommissionsByReseller = `-- name: GetCommissionsByReseller :many
SELECT id, reseller_id, product_id, amount, status, created_at FROM commissions
WHERE reseller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCommissionsByReseller(ctx context.Context, resellerID uuid.UUID) ([]Commission, error) {
	rows, err := q.db.QueryContext(ctx, getCommissionsByReseller, resellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commission
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.ResellerID,
			&i.ProductID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCommission = `-- name: GetPendingCommission :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE reseller_id = $1 AND status = 'PENDING'
`

func (q *Queries) GetPendingCommission(ctx context.Context, resellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingCommission, resellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getResellerCommissions = `-- name: GetResellerCommissions :many
SELECT c.id, c.reseller_id, c.product_id, c.amount, c.status, c.created_at, p.title as product_title 
FROM commissions c
JOIN products p ON c.product_id = p.id
WHERE c.reseller_id = $1
ORDER BY c.created_at DESC
`

type GetResellerCommissionsRow struct {
	ID           uuid.UUID `json:"id"`
	ResellerID   uuid.UUID `json:"reseller_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Amount       int64     `json:"amount"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	ProductTitle string    `json:"product_title"`
}

func (q *Queries) GetResellerCommissions(ctx context.Context, resellerID uuid.UUID) ([]GetResellerCommissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getResellerCommissions, resellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResellerCommissionsRow
	for rows.Next() {
		var i GetResellerCommissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResellerID,
			&i.ProductID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCommission = `-- name: GetTotalCommission :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE reseller_id = $1 AND status = 'PAID'
`

func (q *Queries) GetTotalCommission(ctx context.Context, resellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCommission, resellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalCommissionAll = `-- name: GetTotalCommissionAll :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM commissions WHERE reseller_id = $1
`

func (q *Queries) GetTotalCommissionAll(ctx context.Context, resellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCommissionAll, resellerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
