// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dana.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRegistrationPayment = `-- name: CreateRegistrationPayment :one
INSERT INTO registration_payments (
    user_id, user_type, invoice_number, amount, status, payment_url, external_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, user_type, invoice_number, amount, status, payment_url, external_id, created_at, updated_at
`

type CreateRegistrationPaymentParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	UserType      string         `json:"user_type"`
	InvoiceNumber string         `json:"invoice_number"`
	Amount        int64          `json:"amount"`
	Status        string         `json:"status"`
	PaymentUrl    sql.NullString `json:"payment_url"`
	ExternalID    sql.NullString `json:"external_id"`
}

func (q *Queries) CreateRegistrationPayment(ctx context.Context, arg CreateRegistrationPaymentParams) (RegistrationPayment, error) {
	row := q.db.QueryRowContext(ctx, createRegistrationPayment,
		arg.UserID,
		arg.UserType,
		arg.InvoiceNumber,
		arg.Amount,
		arg.Status,
		arg.PaymentUrl,
		arg.ExternalID,
	)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Status,
		&i.PaymentUrl,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationPaymentByInvoice = `-- name: GetRegistrationPaymentByInvoice :one
SELECT id, user_id, user_type, invoice_number, amount, status, payment_url, external_id, created_at, updated_at FROM registration_payments
WHERE invoice_number = $1 LIMIT 1
`

func (q *Queries) GetRegistrationPaymentByInvoice(ctx context.Context, invoiceNumber string) (RegistrationPayment, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationPaymentByInvoice, invoiceNumber)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Status,
		&i.PaymentUrl,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationPaymentByUserID = `-- name: GetRegistrationPaymentByUserID :one
SELECT id, user_id, user_type, invoice_number, amount, status, payment_url, external_id, created_at, updated_at FROM registration_payments
WHERE user_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetRegistrationPaymentByUserID(ctx context.Context, userID uuid.UUID) (RegistrationPayment, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationPaymentByUserID, userID)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Status,
		&i.PaymentUrl,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberDanaPhone = `-- name: UpdateMemberDanaPhone :one
UPDATE members
SET dana_phone = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateMemberDanaPhoneParams struct {
	ID        uuid.UUID      `json:"id"`
	DanaPhone sql.NullString `json:"dana_phone"`
}

func (q *Queries) UpdateMemberDanaPhone(ctx context.Context, arg UpdateMemberDanaPhoneParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMemberDanaPhone, arg.ID, arg.DanaPhone)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE members
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateMemberStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMemberStatus, arg.ID, arg.Status)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const updatePayoutDanaStatus = `-- name: UpdatePayoutDanaStatus :one
UPDATE payouts
SET status = $2, dana_transaction_id = $3, merchant_trans_id = $4, failed_reason = $5
WHERE id = $1
RETURNING id, user_id, amount, proof_object_key, notes, created_at, user_type, status, dana_transaction_id, merchant_trans_id, failed_reason
`

type UpdatePayoutDanaStatusParams struct {
	ID                uuid.UUID      `json:"id"`
	Status            string         `json:"status"`
	DanaTransactionID sql.NullString `json:"dana_transaction_id"`
	MerchantTransID   sql.NullString `json:"merchant_trans_id"`
	FailedReason      sql.NullString `json:"failed_reason"`
}

func (q *Queries) UpdatePayoutDanaStatus(ctx context.Context, arg UpdatePayoutDanaStatusParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, updatePayoutDanaStatus,
		arg.ID,
		arg.Status,
		arg.DanaTransactionID,
		arg.MerchantTransID,
		arg.FailedReason,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.ProofObjectKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UserType,
		&i.Status,
		&i.DanaTransactionID,
		&i.MerchantTransID,
		&i.FailedReason,
	)
	return i, err
}

const updateRegistrationPaymentStatus = `-- name: UpdateRegistrationPaymentStatus :one
UPDATE registration_payments
SET status = $2, external_id = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, user_type, invoice_number, amount, status, payment_url, external_id, created_at, updated_at
`

type UpdateRegistrationPaymentStatusParams struct {
	ID         uuid.UUID      `json:"id"`
	Status     string         `json:"status"`
	ExternalID sql.NullString `json:"external_id"`
}

func (q *Queries) UpdateRegistrationPaymentStatus(ctx context.Context, arg UpdateRegistrationPaymentStatusParams) (RegistrationPayment, error) {
	row := q.db.QueryRowContext(ctx, updateRegistrationPaymentStatus, arg.ID, arg.Status, arg.ExternalID)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Status,
		&i.PaymentUrl,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResellerDanaPhone = `-- name: UpdateResellerDanaPhone :one
UPDATE resellers
SET dana_phone = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateResellerDanaPhoneParams struct {
	ID        uuid.UUID      `json:"id"`
	DanaPhone sql.NullString `json:"dana_phone"`
}

func (q *Queries) UpdateResellerDanaPhone(ctx context.Context, arg UpdateResellerDanaPhoneParams) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, updateResellerDanaPhone, arg.ID, arg.DanaPhone)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const updateResellerStatus = `-- name: UpdateResellerStatus :one
UPDATE resellers
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateResellerStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateResellerStatus(ctx context.Context, arg UpdateResellerStatusParams) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, updateResellerStatus, arg.ID, arg.Status)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}
