// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, token)
	return err
}

const getDeviceTokensByRoles = `-- name: GetDeviceTokensByRoles :many
SELECT id, user_id, role, token, device_type, created_at, updated_at FROM device_tokens
WHERE role = ANY($1::text[])
`

func (q *Queries) GetDeviceTokensByRoles(ctx context.Context, dollar_1 []string) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTokensByRoles, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Token,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTokensByUserIdAndRole = `-- name: GetDeviceTokensByUserIdAndRole :many
SELECT id, user_id, role, token, device_type, created_at, updated_at FROM device_tokens
WHERE user_id = $1 AND role = $2
`

type GetDeviceTokensByUserIdAndRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) GetDeviceTokensByUserIdAndRole(ctx context.Context, arg GetDeviceTokensByUserIdAndRoleParams) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTokensByUserIdAndRole, arg.UserID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Token,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTokensByUserIdsAndRole = `-- name: GetDeviceTokensByUserIdsAndRole :many
SELECT id, user_id, role, token, device_type, created_at, updated_at FROM device_tokens
WHERE user_id = ANY($1::uuid[]) AND role = $2
`

type GetDeviceTokensByUserIdsAndRoleParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Role    string      `json:"role"`
}

func (q *Queries) GetDeviceTokensByUserIdsAndRole(ctx context.Context, arg GetDeviceTokensByUserIdsAndRoleParams) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTokensByUserIdsAndRole, pq.Array(arg.Column1), arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Token,
			&i.DeviceType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (
    user_id, role, token, device_type
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    role = EXCLUDED.role,
    device_type = EXCLUDED.device_type,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, role, token, device_type, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Role       string    `json:"role"`
	Token      string    `json:"token"`
	DeviceType string    `json:"device_type"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, upsertDeviceToken,
		arg.UserID,
		arg.Role,
		arg.Token,
		arg.DeviceType,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Token,
		&i.DeviceType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
