// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLead = `-- name: CreateLead :one
INSERT INTO product_leads (
    product_id, reseller_id, member_id, visitor_phone, visitor_name, client_id 
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, product_id, reseller_id, client_id, status, created_at, visitor_phone, visitor_name, member_id
`

type CreateLeadParams struct {
	ProductID    uuid.UUID      `json:"product_id"`
	ResellerID   uuid.NullUUID  `json:"reseller_id"`
	MemberID     uuid.NullUUID  `json:"member_id"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	VisitorName  sql.NullString `json:"visitor_name"`
	ClientID     uuid.NullUUID  `json:"client_id"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (ProductLead, error) {
	row := q.db.QueryRowContext(ctx, createLead,
		arg.ProductID,
		arg.ResellerID,
		arg.MemberID,
		arg.VisitorPhone,
		arg.VisitorName,
		arg.ClientID,
	)
	var i ProductLead
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ResellerID,
		&i.ClientID,
		&i.Status,
		&i.CreatedAt,
		&i.VisitorPhone,
		&i.VisitorName,
		&i.MemberID,
	)
	return i, err
}

const getLeadsByProduct = `-- name: GetLeadsByProduct :many
SELECT l.id, l.product_id, l.reseller_id, l.client_id, l.status, l.created_at, l.visitor_phone, l.visitor_name, l.member_id, 
       COALESCE(r.referral_code, m.referral_code, '') as referral_code, 
       COALESCE(r.name, m.name, '') as reseller_name 
FROM product_leads l
LEFT JOIN resellers r ON l.reseller_id = r.id
LEFT JOIN members m ON l.member_id = m.id
WHERE l.product_id = $1
ORDER BY l.created_at DESC
`

type GetLeadsByProductRow struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	ResellerID   uuid.NullUUID  `json:"reseller_id"`
	ClientID     uuid.NullUUID  `json:"client_id"`
	Status       LeadStatus     `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	VisitorName  sql.NullString `json:"visitor_name"`
	MemberID     uuid.NullUUID  `json:"member_id"`
	ReferralCode string         `json:"referral_code"`
	ResellerName string         `json:"reseller_name"`
}

func (q *Queries) GetLeadsByProduct(ctx context.Context, productID uuid.UUID) ([]GetLeadsByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeadsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeadsByProductRow
	for rows.Next() {
		var i GetLeadsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ResellerID,
			&i.ClientID,
			&i.Status,
			&i.CreatedAt,
			&i.VisitorPhone,
			&i.VisitorName,
			&i.MemberID,
			&i.ReferralCode,
			&i.ResellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeadsByReseller = `-- name: GetLeadsByReseller :many
SELECT id, product_id, reseller_id, client_id, status, created_at, visitor_phone, visitor_name, member_id FROM product_leads
WHERE reseller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLeadsByReseller(ctx context.Context, resellerID uuid.NullUUID) ([]ProductLead, error) {
	rows, err := q.db.QueryContext(ctx, getLeadsByReseller, resellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductLead
	for rows.Next() {
		var i ProductLead
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ResellerID,
			&i.ClientID,
			&i.Status,
			&i.CreatedAt,
			&i.VisitorPhone,
			&i.VisitorName,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberRecentActivities = `-- name: GetMemberRecentActivities :many
SELECT 
    'LEAD' as activity_type,
    l.id, 
    l.visitor_name as visitor_name, 
    l.visitor_phone as visitor_phone, 
    p.id as product_id, 
    p.title as product_title, 
    0::bigint as commission_amount,
    l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
LEFT JOIN resellers r ON l.reseller_id = r.id
WHERE r.member_id = $1 OR l.member_id = $1
UNION ALL
SELECT 
    'SALE' as activity_type,
    c.id,
    '' as visitor_name,
    '' as visitor_phone,
    p.id as product_id,
    p.title as product_title,
    c.amount as commission_amount,
    c.created_at
FROM commissions c
JOIN products p ON c.product_id = p.id
WHERE c.user_id = $1 AND c.user_type = 'MEMBER'
ORDER BY created_at DESC
LIMIT $2
`

type GetMemberRecentActivitiesParams struct {
	MemberID uuid.NullUUID `json:"member_id"`
	Limit    int32         `json:"limit"`
}

type GetMemberRecentActivitiesRow struct {
	ActivityType     string         `json:"activity_type"`
	ID               uuid.UUID      `json:"id"`
	VisitorName      sql.NullString `json:"visitor_name"`
	VisitorPhone     sql.NullString `json:"visitor_phone"`
	ProductID        uuid.UUID      `json:"product_id"`
	ProductTitle     string         `json:"product_title"`
	CommissionAmount int64          `json:"commission_amount"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) GetMemberRecentActivities(ctx context.Context, arg GetMemberRecentActivitiesParams) ([]GetMemberRecentActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemberRecentActivities, arg.MemberID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberRecentActivitiesRow
	for rows.Next() {
		var i GetMemberRecentActivitiesRow
		if err := rows.Scan(
			&i.ActivityType,
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberStats = `-- name: GetMemberStats :one
SELECT 
    COUNT(l.id) as total_leads, 
    (SELECT COUNT(*) FROM member_products mp WHERE mp.member_id = $1)::bigint as total_shares 
FROM product_leads l
LEFT JOIN resellers r ON l.reseller_id = r.id
WHERE r.member_id = $1 OR l.member_id = $1
`

type GetMemberStatsRow struct {
	TotalLeads  int64 `json:"total_leads"`
	TotalShares int64 `json:"total_shares"`
}

func (q *Queries) GetMemberStats(ctx context.Context, memberID uuid.UUID) (GetMemberStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberStats, memberID)
	var i GetMemberStatsRow
	err := row.Scan(&i.TotalLeads, &i.TotalShares)
	return i, err
}

const getMemberTeamStats = `-- name: GetMemberTeamStats :one
SELECT 
    COUNT(c.id) as total_sales,
    COALESCE(SUM(c.amount), 0)::bigint as total_commission
FROM commissions c
JOIN resellers r ON c.user_id = r.id
WHERE r.member_id = $1 AND c.user_type = 'RESELLER'
`

type GetMemberTeamStatsRow struct {
	TotalSales      int64 `json:"total_sales"`
	TotalCommission int64 `json:"total_commission"`
}

func (q *Queries) GetMemberTeamStats(ctx context.Context, memberID uuid.NullUUID) (GetMemberTeamStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberTeamStats, memberID)
	var i GetMemberTeamStatsRow
	err := row.Scan(&i.TotalSales, &i.TotalCommission)
	return i, err
}

const getRecentLeads = `-- name: GetRecentLeads :many
SELECT l.id, l.visitor_name, l.visitor_phone, p.id as product_id, p.title as product_title, 
       COALESCE(r.referral_code, m.referral_code) as referral_code, 
       COALESCE(r.name, m.name) as reseller_name, l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
LEFT JOIN resellers r ON l.reseller_id = r.id 
LEFT JOIN members m ON l.member_id = m.id
ORDER BY l.created_at DESC 
LIMIT $1
`

type GetRecentLeadsRow struct {
	ID           uuid.UUID      `json:"id"`
	VisitorName  sql.NullString `json:"visitor_name"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	ProductID    uuid.UUID      `json:"product_id"`
	ProductTitle string         `json:"product_title"`
	ReferralCode string         `json:"referral_code"`
	ResellerName string         `json:"reseller_name"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) GetRecentLeads(ctx context.Context, limit int32) ([]GetRecentLeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentLeads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLeadsRow
	for rows.Next() {
		var i GetRecentLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.ReferralCode,
			&i.ResellerName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerRecentActivities = `-- name: GetResellerRecentActivities :many
SELECT 
    'LEAD' as activity_type,
    l.id, 
    l.visitor_name as visitor_name, 
    l.visitor_phone as visitor_phone, 
    p.id as product_id, 
    p.title as product_title, 
    0::bigint as commission_amount,
    l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
WHERE l.reseller_id = $1
UNION ALL
SELECT 
    'SALE' as activity_type,
    c.id,
    '' as visitor_name,
    '' as visitor_phone,
    p.id as product_id,
    p.title as product_title,
    c.amount as commission_amount,
    c.created_at
FROM commissions c
JOIN products p ON c.product_id = p.id
WHERE c.user_id = $1 AND c.user_type = 'RESELLER'
ORDER BY created_at DESC
LIMIT $2
`

type GetResellerRecentActivitiesParams struct {
	ResellerID uuid.NullUUID `json:"reseller_id"`
	Limit      int32         `json:"limit"`
}

type GetResellerRecentActivitiesRow struct {
	ActivityType     string         `json:"activity_type"`
	ID               uuid.UUID      `json:"id"`
	VisitorName      sql.NullString `json:"visitor_name"`
	VisitorPhone     sql.NullString `json:"visitor_phone"`
	ProductID        uuid.UUID      `json:"product_id"`
	ProductTitle     string         `json:"product_title"`
	CommissionAmount int64          `json:"commission_amount"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) GetResellerRecentActivities(ctx context.Context, arg GetResellerRecentActivitiesParams) ([]GetResellerRecentActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getResellerRecentActivities, arg.ResellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResellerRecentActivitiesRow
	for rows.Next() {
		var i GetResellerRecentActivitiesRow
		if err := rows.Scan(
			&i.ActivityType,
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerRecentLeads = `-- name: GetResellerRecentLeads :many
SELECT l.id, l.visitor_name, l.visitor_phone, p.id as product_id, p.title as product_title, l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
WHERE l.reseller_id = $1 
ORDER BY l.created_at DESC 
LIMIT $2
`

type GetResellerRecentLeadsParams struct {
	ResellerID uuid.NullUUID `json:"reseller_id"`
	Limit      int32         `json:"limit"`
}

type GetResellerRecentLeadsRow struct {
	ID           uuid.UUID      `json:"id"`
	VisitorName  sql.NullString `json:"visitor_name"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	ProductID    uuid.UUID      `json:"product_id"`
	ProductTitle string         `json:"product_title"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) GetResellerRecentLeads(ctx context.Context, arg GetResellerRecentLeadsParams) ([]GetResellerRecentLeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getResellerRecentLeads, arg.ResellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResellerRecentLeadsRow
	for rows.Next() {
		var i GetResellerRecentLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerStats = `-- name: GetResellerStats :one
SELECT 
    COUNT(id) as total_leads, 
    (SELECT COUNT(*) FROM product_resellers pr WHERE pr.reseller_id = $1)::bigint as total_shares 
FROM product_leads 
WHERE reseller_id = $1
`

type GetResellerStatsRow struct {
	TotalLeads  int64 `json:"total_leads"`
	TotalShares int64 `json:"total_shares"`
}

func (q *Queries) GetResellerStats(ctx context.Context, resellerID uuid.UUID) (GetResellerStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getResellerStats, resellerID)
	var i GetResellerStatsRow
	err := row.Scan(&i.TotalLeads, &i.TotalShares)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :exec
UPDATE product_leads SET status = $2 WHERE id = $1
`

type UpdateLeadStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status LeadStatus `json:"status"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLeadStatus, arg.ID, arg.Status)
	return err
}
