// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leads.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLead = `-- name: CreateLead :one
INSERT INTO product_leads (
    product_id, reseller_id, visitor_phone, visitor_name, client_id 
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, product_id, reseller_id, client_id, status, created_at, visitor_phone, visitor_name
`

type CreateLeadParams struct {
	ProductID    uuid.UUID      `json:"product_id"`
	ResellerID   uuid.UUID      `json:"reseller_id"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	VisitorName  sql.NullString `json:"visitor_name"`
	ClientID     uuid.NullUUID  `json:"client_id"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (ProductLead, error) {
	row := q.db.QueryRowContext(ctx, createLead,
		arg.ProductID,
		arg.ResellerID,
		arg.VisitorPhone,
		arg.VisitorName,
		arg.ClientID,
	)
	var i ProductLead
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ResellerID,
		&i.ClientID,
		&i.Status,
		&i.CreatedAt,
		&i.VisitorPhone,
		&i.VisitorName,
	)
	return i, err
}

const getLeadsByProduct = `-- name: GetLeadsByProduct :many
SELECT l.id, l.product_id, l.reseller_id, l.client_id, l.status, l.created_at, l.visitor_phone, l.visitor_name, u.referral_code, u.name as reseller_name 
FROM product_leads l
JOIN users u ON l.reseller_id = u.id
WHERE l.product_id = $1
ORDER BY l.created_at DESC
`

type GetLeadsByProductRow struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	ResellerID   uuid.UUID      `json:"reseller_id"`
	ClientID     uuid.NullUUID  `json:"client_id"`
	Status       LeadStatus     `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	VisitorName  sql.NullString `json:"visitor_name"`
	ReferralCode sql.NullString `json:"referral_code"`
	ResellerName string         `json:"reseller_name"`
}

func (q *Queries) GetLeadsByProduct(ctx context.Context, productID uuid.UUID) ([]GetLeadsByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeadsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeadsByProductRow
	for rows.Next() {
		var i GetLeadsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ResellerID,
			&i.ClientID,
			&i.Status,
			&i.CreatedAt,
			&i.VisitorPhone,
			&i.VisitorName,
			&i.ReferralCode,
			&i.ResellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeadsByReseller = `-- name: GetLeadsByReseller :many
SELECT id, product_id, reseller_id, client_id, status, created_at, visitor_phone, visitor_name FROM product_leads
WHERE reseller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLeadsByReseller(ctx context.Context, resellerID uuid.UUID) ([]ProductLead, error) {
	rows, err := q.db.QueryContext(ctx, getLeadsByReseller, resellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductLead
	for rows.Next() {
		var i ProductLead
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ResellerID,
			&i.ClientID,
			&i.Status,
			&i.CreatedAt,
			&i.VisitorPhone,
			&i.VisitorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLeads = `-- name: GetRecentLeads :many
SELECT l.id, l.visitor_name, l.visitor_phone, p.id as product_id, p.title as product_title, u.referral_code, u.name as reseller_name, l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
JOIN users u ON l.reseller_id = u.id 
ORDER BY l.created_at DESC 
LIMIT $1
`

type GetRecentLeadsRow struct {
	ID           uuid.UUID      `json:"id"`
	VisitorName  sql.NullString `json:"visitor_name"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	ProductID    uuid.UUID      `json:"product_id"`
	ProductTitle string         `json:"product_title"`
	ReferralCode sql.NullString `json:"referral_code"`
	ResellerName string         `json:"reseller_name"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) GetRecentLeads(ctx context.Context, limit int32) ([]GetRecentLeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentLeads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLeadsRow
	for rows.Next() {
		var i GetRecentLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.ReferralCode,
			&i.ResellerName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerRecentActivities = `-- name: GetResellerRecentActivities :many
SELECT 
    'LEAD' as activity_type,
    l.id, 
    l.visitor_name as visitor_name, 
    l.visitor_phone as visitor_phone, 
    p.id as product_id, 
    p.title as product_title, 
    0::bigint as commission_amount,
    l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
WHERE l.reseller_id = $1
UNION ALL
SELECT 
    'SALE' as activity_type,
    c.id,
    '' as visitor_name,
    '' as visitor_phone,
    p.id as product_id,
    p.title as product_title,
    c.amount as commission_amount,
    c.created_at
FROM commissions c
JOIN products p ON c.product_id = p.id
WHERE c.reseller_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetResellerRecentActivitiesParams struct {
	ResellerID uuid.UUID `json:"reseller_id"`
	Limit      int32     `json:"limit"`
}

type GetResellerRecentActivitiesRow struct {
	ActivityType     string         `json:"activity_type"`
	ID               uuid.UUID      `json:"id"`
	VisitorName      sql.NullString `json:"visitor_name"`
	VisitorPhone     sql.NullString `json:"visitor_phone"`
	ProductID        uuid.UUID      `json:"product_id"`
	ProductTitle     string         `json:"product_title"`
	CommissionAmount int64          `json:"commission_amount"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) GetResellerRecentActivities(ctx context.Context, arg GetResellerRecentActivitiesParams) ([]GetResellerRecentActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getResellerRecentActivities, arg.ResellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResellerRecentActivitiesRow
	for rows.Next() {
		var i GetResellerRecentActivitiesRow
		if err := rows.Scan(
			&i.ActivityType,
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerRecentLeads = `-- name: GetResellerRecentLeads :many
SELECT l.id, l.visitor_name, l.visitor_phone, p.id as product_id, p.title as product_title, l.created_at 
FROM product_leads l 
JOIN products p ON l.product_id = p.id 
WHERE l.reseller_id = $1 
ORDER BY l.created_at DESC 
LIMIT $2
`

type GetResellerRecentLeadsParams struct {
	ResellerID uuid.UUID `json:"reseller_id"`
	Limit      int32     `json:"limit"`
}

type GetResellerRecentLeadsRow struct {
	ID           uuid.UUID      `json:"id"`
	VisitorName  sql.NullString `json:"visitor_name"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	ProductID    uuid.UUID      `json:"product_id"`
	ProductTitle string         `json:"product_title"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) GetResellerRecentLeads(ctx context.Context, arg GetResellerRecentLeadsParams) ([]GetResellerRecentLeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getResellerRecentLeads, arg.ResellerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResellerRecentLeadsRow
	for rows.Next() {
		var i GetResellerRecentLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.ProductID,
			&i.ProductTitle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResellerStats = `-- name: GetResellerStats :one
SELECT COUNT(*) as total_leads, COUNT(DISTINCT product_id) as active_products FROM product_leads WHERE reseller_id = $1
`

type GetResellerStatsRow struct {
	TotalLeads     int64 `json:"total_leads"`
	ActiveProducts int64 `json:"active_products"`
}

func (q *Queries) GetResellerStats(ctx context.Context, resellerID uuid.UUID) (GetResellerStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getResellerStats, resellerID)
	var i GetResellerStatsRow
	err := row.Scan(&i.TotalLeads, &i.ActiveProducts)
	return i, err
}
