// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mart_clients.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addMartClientFavorite = `-- name: AddMartClientFavorite :exec
INSERT INTO mart_client_favorites (client_id, product_id)
VALUES ($1, $2)
ON CONFLICT (client_id, product_id) DO NOTHING
`

type AddMartClientFavoriteParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) AddMartClientFavorite(ctx context.Context, arg AddMartClientFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addMartClientFavorite, arg.ClientID, arg.ProductID)
	return err
}

const checkReferralCodeExists = `-- name: CheckReferralCodeExists :one
SELECT 
    TRUE::BOOLEAN as is_exists,
    'MEMBER'::TEXT as user_type,
    id as referrer_id
FROM members WHERE referral_code = $1::VARCHAR AND status = 'ACTIVE'
UNION ALL
SELECT 
    TRUE::BOOLEAN as is_exists,
    'RESELLER'::TEXT as user_type,
    id as referrer_id
FROM resellers WHERE referral_code = $1::VARCHAR AND status = 'ACTIVE'
LIMIT 1
`

type CheckReferralCodeExistsRow struct {
	IsExists   bool      `json:"is_exists"`
	UserType   string    `json:"user_type"`
	ReferrerID uuid.UUID `json:"referrer_id"`
}

// Check if referral code exists in members OR resellers table
func (q *Queries) CheckReferralCodeExists(ctx context.Context, referralCode string) (CheckReferralCodeExistsRow, error) {
	row := q.db.QueryRowContext(ctx, checkReferralCodeExists, referralCode)
	var i CheckReferralCodeExistsRow
	err := row.Scan(&i.IsExists, &i.UserType, &i.ReferrerID)
	return i, err
}

const getMartClientByID = `-- name: GetMartClientByID :one
SELECT id, google_id, email, name, phone, referral_code_used, status, created_at, updated_at FROM mart_clients WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMartClientByID(ctx context.Context, id uuid.UUID) (MartClient, error) {
	row := q.db.QueryRowContext(ctx, getMartClientByID, id)
	var i MartClient
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.ReferralCodeUsed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMartClientFavoriteExists = `-- name: GetMartClientFavoriteExists :one
SELECT EXISTS (
    SELECT 1 FROM mart_client_favorites
    WHERE client_id = $1 AND product_id = $2
) AS is_favorite
`

type GetMartClientFavoriteExistsParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) GetMartClientFavoriteExists(ctx context.Context, arg GetMartClientFavoriteExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getMartClientFavoriteExists, arg.ClientID, arg.ProductID)
	var is_favorite bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const listMartClientFavorites = `-- name: ListMartClientFavorites :many
SELECT 
    p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock, p.member_commission_amount, p.reseller_commission_amount, p.specifications,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM mart_client_favorites mcf
JOIN products p ON mcf.product_id = p.id
WHERE mcf.client_id = $1
ORDER BY mcf.created_at DESC
`

type ListMartClientFavoritesRow struct {
	ID                       uuid.UUID       `json:"id"`
	CategoryID               uuid.UUID       `json:"category_id"`
	Title                    string          `json:"title"`
	Description              string          `json:"description"`
	Price                    int64           `json:"price"`
	Status                   ProductStatus   `json:"status"`
	CreatedBy                uuid.UUID       `json:"created_by"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	CommissionAmount         int64           `json:"commission_amount"`
	LocationName             sql.NullString  `json:"location_name"`
	Latitude                 sql.NullString  `json:"latitude"`
	Longitude                sql.NullString  `json:"longitude"`
	Province                 sql.NullString  `json:"province"`
	Regency                  sql.NullString  `json:"regency"`
	District                 sql.NullString  `json:"district"`
	Village                  sql.NullString  `json:"village"`
	Stock                    int32           `json:"stock"`
	MemberCommissionAmount   int64           `json:"member_commission_amount"`
	ResellerCommissionAmount int64           `json:"reseller_commission_amount"`
	Specifications           json.RawMessage `json:"specifications"`
	ThumbnailUrl             string          `json:"thumbnail_url"`
}

func (q *Queries) ListMartClientFavorites(ctx context.Context, clientID uuid.UUID) ([]ListMartClientFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMartClientFavorites, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMartClientFavoritesRow
	for rows.Next() {
		var i ListMartClientFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionAmount,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.Village,
			&i.Stock,
			&i.MemberCommissionAmount,
			&i.ResellerCommissionAmount,
			&i.Specifications,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMartClients = `-- name: ListMartClients :many
SELECT id, google_id, email, name, phone, referral_code_used, status, created_at, updated_at FROM mart_clients 
WHERE ($1::TEXT = '' OR name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%' OR phone ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
`

func (q *Queries) ListMartClients(ctx context.Context, dollar_1 string) ([]MartClient, error) {
	rows, err := q.db.QueryContext(ctx, listMartClients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MartClient
	for rows.Next() {
		var i MartClient
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.ReferralCodeUsed,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMartClientFavorite = `-- name: RemoveMartClientFavorite :exec
DELETE FROM mart_client_favorites
WHERE client_id = $1 AND product_id = $2
`

type RemoveMartClientFavoriteParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveMartClientFavorite(ctx context.Context, arg RemoveMartClientFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeMartClientFavorite, arg.ClientID, arg.ProductID)
	return err
}

const updateMartClientProfile = `-- name: UpdateMartClientProfile :one
UPDATE mart_clients
SET 
    name = $2,
    phone = $3,
    referral_code_used = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, google_id, email, name, phone, referral_code_used, status, created_at, updated_at
`

type UpdateMartClientProfileParams struct {
	ID               uuid.UUID      `json:"id"`
	Name             sql.NullString `json:"name"`
	Phone            sql.NullString `json:"phone"`
	ReferralCodeUsed sql.NullString `json:"referral_code_used"`
}

func (q *Queries) UpdateMartClientProfile(ctx context.Context, arg UpdateMartClientProfileParams) (MartClient, error) {
	row := q.db.QueryRowContext(ctx, updateMartClientProfile,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.ReferralCodeUsed,
	)
	var i MartClient
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.ReferralCodeUsed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMartClientFromGoogle = `-- name: UpsertMartClientFromGoogle :one
INSERT INTO mart_clients (google_id, email, status, created_at, updated_at)
VALUES ($1, $2, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO UPDATE 
SET 
    google_id = COALESCE(mart_clients.google_id, EXCLUDED.google_id),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, google_id, email, name, phone, referral_code_used, status, created_at, updated_at
`

type UpsertMartClientFromGoogleParams struct {
	GoogleID sql.NullString `json:"google_id"`
	Email    string         `json:"email"`
}

func (q *Queries) UpsertMartClientFromGoogle(ctx context.Context, arg UpsertMartClientFromGoogleParams) (MartClient, error) {
	row := q.db.QueryRowContext(ctx, upsertMartClientFromGoogle, arg.GoogleID, arg.Email)
	var i MartClient
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.ReferralCodeUsed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
