// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    name, phone, email, password_hash, referral_code, status, username, nik, profile_image, ktp_image
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type CreateMemberParams struct {
	Name         string         `json:"name"`
	Phone        string         `json:"phone"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	ReferralCode string         `json:"referral_code"`
	Status       UserStatus     `json:"status"`
	Username     sql.NullString `json:"username"`
	Nik          sql.NullString `json:"nik"`
	ProfileImage sql.NullString `json:"profile_image"`
	KtpImage     sql.NullString `json:"ktp_image"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.ReferralCode,
		arg.Status,
		arg.Username,
		arg.Nik,
		arg.ProfileImage,
		arg.KtpImage,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const getMemberByPhone = `-- name: GetMemberByPhone :one
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetMemberByPhone(ctx context.Context, phone string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByPhone, phone)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const getMemberByReferralCode = `-- name: GetMemberByReferralCode :one
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetMemberByReferralCode(ctx context.Context, referralCode string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByReferralCode, referralCode)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const getMemberByUsername = `-- name: GetMemberByUsername :one
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetMemberByUsername(ctx context.Context, username sql.NullString) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByUsername, username)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
ORDER BY created_at DESC
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Nik,
			&i.ProfileImage,
			&i.KtpImage,
			&i.Bio,
			&i.PhoneVerifiedAt,
			&i.DanaPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembers = `-- name: ListPendingMembers :many
SELECT id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM members
WHERE status = 'PENDING'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Nik,
			&i.ProfileImage,
			&i.KtpImage,
			&i.Bio,
			&i.PhoneVerifiedAt,
			&i.DanaPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMemberPhoneVerified = `-- name: MarkMemberPhoneVerified :one
UPDATE members
SET phone_verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING phone_verified_at
`

func (q *Queries) MarkMemberPhoneVerified(ctx context.Context, id uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, markMemberPhoneVerified, id)
	var phone_verified_at sql.NullTime
	err := row.Scan(&phone_verified_at)
	return phone_verified_at, err
}

const trackMemberShare = `-- name: TrackMemberShare :exec
INSERT INTO member_products (member_id, product_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type TrackMemberShareParams struct {
	MemberID  uuid.UUID `json:"member_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) TrackMemberShare(ctx context.Context, arg TrackMemberShareParams) error {
	_, err := q.db.ExecContext(ctx, trackMemberShare, arg.MemberID, arg.ProductID)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET name = $2, phone = $3, email = $4, status = $5, username = $6, nik = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateMemberParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Phone    string         `json:"phone"`
	Email    sql.NullString `json:"email"`
	Status   UserStatus     `json:"status"`
	Username sql.NullString `json:"username"`
	Nik      sql.NullString `json:"nik"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.Username,
		arg.Nik,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const updateMemberProfile = `-- name: UpdateMemberProfile :one
UPDATE members
SET name = $2, email = $3, bio = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateMemberProfileParams struct {
	ID    uuid.UUID      `json:"id"`
	Name  string         `json:"name"`
	Email sql.NullString `json:"email"`
	Bio   sql.NullString `json:"bio"`
}

func (q *Queries) UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMemberProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Bio,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}
