// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AdminRole string

const (
	AdminRoleSUPERADMIN AdminRole = "SUPER_ADMIN"
	AdminRoleADMIN      AdminRole = "ADMIN"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type AssetType string

const (
	AssetTypeIMAGE AssetType = "IMAGE"
	AssetTypeVIDEO AssetType = "VIDEO"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type CommissionUserType string

const (
	CommissionUserTypeMEMBER   CommissionUserType = "MEMBER"
	CommissionUserTypeRESELLER CommissionUserType = "RESELLER"
)

func (e *CommissionUserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommissionUserType(s)
	case string:
		*e = CommissionUserType(s)
	default:
		return fmt.Errorf("unsupported scan type for CommissionUserType: %T", src)
	}
	return nil
}

type NullCommissionUserType struct {
	CommissionUserType CommissionUserType `json:"commission_user_type"`
	Valid              bool               `json:"valid"` // Valid is true if CommissionUserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommissionUserType) Scan(value interface{}) error {
	if value == nil {
		ns.CommissionUserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommissionUserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommissionUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommissionUserType), nil
}

type LeadStatus string

const (
	LeadStatusNEW       LeadStatus = "NEW"
	LeadStatusCONTACTED LeadStatus = "CONTACTED"
	LeadStatusDEAL      LeadStatus = "DEAL"
	LeadStatusCANCEL    LeadStatus = "CANCEL"
)

func (e *LeadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadStatus(s)
	case string:
		*e = LeadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadStatus: %T", src)
	}
	return nil
}

type NullLeadStatus struct {
	LeadStatus LeadStatus `json:"lead_status"`
	Valid      bool       `json:"valid"` // Valid is true if LeadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadStatus), nil
}

type ProductStatus string

const (
	ProductStatusDRAFT    ProductStatus = "DRAFT"
	ProductStatusACTIVE   ProductStatus = "ACTIVE"
	ProductStatusSOLD     ProductStatus = "SOLD"
	ProductStatusINACTIVE ProductStatus = "INACTIVE"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type UserRole string

const (
	UserRoleRESELLER UserRole = "RESELLER"
	UserRoleCLIENT   UserRole = "CLIENT"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusPENDING UserStatus = "PENDING"
	UserStatusACTIVE  UserStatus = "ACTIVE"
	UserStatusBLOCKED UserStatus = "BLOCKED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Admin struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         AdminRole `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Commission struct {
	ID           uuid.UUID          `json:"id"`
	ProductID    uuid.NullUUID      `json:"product_id"`
	Amount       int64              `json:"amount"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
	UserType     CommissionUserType `json:"user_type"`
	UserID       uuid.NullUUID      `json:"user_id"`
	ReferralCode sql.NullString     `json:"referral_code"`
}

type DeviceToken struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Role       string    `json:"role"`
	Token      string    `json:"token"`
	DeviceType string    `json:"device_type"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MartClient struct {
	ID               uuid.UUID      `json:"id"`
	GoogleID         sql.NullString `json:"google_id"`
	Email            string         `json:"email"`
	Name             sql.NullString `json:"name"`
	Phone            sql.NullString `json:"phone"`
	ReferralCodeUsed sql.NullString `json:"referral_code_used"`
	Status           UserStatus     `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type MartClientFavorite struct {
	ClientID  uuid.UUID `json:"client_id"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Member struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Phone           string         `json:"phone"`
	Email           sql.NullString `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	ReferralCode    string         `json:"referral_code"`
	Status          UserStatus     `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Username        sql.NullString `json:"username"`
	Nik             sql.NullString `json:"nik"`
	ProfileImage    sql.NullString `json:"profile_image"`
	KtpImage        sql.NullString `json:"ktp_image"`
	Bio             sql.NullString `json:"bio"`
	PhoneVerifiedAt sql.NullTime   `json:"phone_verified_at"`
	DanaPhone       sql.NullString `json:"dana_phone"`
}

type MemberProduct struct {
	MemberID  uuid.UUID `json:"member_id"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Payout struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Amount            int64          `json:"amount"`
	ProofObjectKey    sql.NullString `json:"proof_object_key"`
	Notes             sql.NullString `json:"notes"`
	CreatedAt         time.Time      `json:"created_at"`
	UserType          string         `json:"user_type"`
	Status            string         `json:"status"`
	DanaTransactionID sql.NullString `json:"dana_transaction_id"`
	MerchantTransID   sql.NullString `json:"merchant_trans_id"`
	FailedReason      sql.NullString `json:"failed_reason"`
}

type Product struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	// Jumlah stok produk yang tersedia. 0 = Habis, >0 = Tersedia
	Stock                    int32           `json:"stock"`
	MemberCommissionAmount   int64           `json:"member_commission_amount"`
	ResellerCommissionAmount int64           `json:"reseller_commission_amount"`
	Specifications           json.RawMessage `json:"specifications"`
}

type ProductAsset struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	AssetType AssetType `json:"asset_type"`
	ObjectKey string    `json:"object_key"`
	CreatedAt time.Time `json:"created_at"`
}

type ProductClick struct {
	ID         uuid.UUID      `json:"id"`
	ProductID  uuid.UUID      `json:"product_id"`
	ResellerID uuid.UUID      `json:"reseller_id"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	ClickedAt  time.Time      `json:"clicked_at"`
}

type ProductLead struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	ResellerID   uuid.NullUUID  `json:"reseller_id"`
	ClientID     uuid.NullUUID  `json:"client_id"`
	Status       LeadStatus     `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	VisitorPhone sql.NullString `json:"visitor_phone"`
	VisitorName  sql.NullString `json:"visitor_name"`
	MemberID     uuid.NullUUID  `json:"member_id"`
}

type ProductReseller struct {
	ID           uuid.UUID `json:"id"`
	ProductID    uuid.UUID `json:"product_id"`
	ResellerID   uuid.UUID `json:"reseller_id"`
	ReferralCode string    `json:"referral_code"`
	CreatedAt    time.Time `json:"created_at"`
}

type ProductVerification struct {
	ID         uuid.UUID    `json:"id"`
	ProductID  uuid.UUID    `json:"product_id"`
	ResellerID uuid.UUID    `json:"reseller_id"`
	ClientID   uuid.UUID    `json:"client_id"`
	Phone      string       `json:"phone"`
	VerifiedAt time.Time    `json:"verified_at"`
	ExpiredAt  sql.NullTime `json:"expired_at"`
}

type RegistrationPayment struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	UserType      string         `json:"user_type"`
	InvoiceNumber string         `json:"invoice_number"`
	Amount        int64          `json:"amount"`
	Status        string         `json:"status"`
	PaymentUrl    sql.NullString `json:"payment_url"`
	ExternalID    sql.NullString `json:"external_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Reseller struct {
	ID              uuid.UUID      `json:"id"`
	MemberID        uuid.NullUUID  `json:"member_id"`
	Name            string         `json:"name"`
	Phone           string         `json:"phone"`
	Email           sql.NullString `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	ReferralCode    string         `json:"referral_code"`
	Status          UserStatus     `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Username        sql.NullString `json:"username"`
	Nik             sql.NullString `json:"nik"`
	ProfileImage    sql.NullString `json:"profile_image"`
	KtpImage        sql.NullString `json:"ktp_image"`
	Bio             sql.NullString `json:"bio"`
	PhoneVerifiedAt sql.NullTime   `json:"phone_verified_at"`
	DanaPhone       sql.NullString `json:"dana_phone"`
}

type SystemConfig struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Phone        string         `json:"phone"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         UserRole       `json:"role"`
	ReferralCode sql.NullString `json:"referral_code"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
