// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
    user_id, amount, proof_object_key, notes, user_type
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, amount, proof_object_key, notes, created_at, user_type, status, dana_transaction_id, merchant_trans_id, failed_reason
`

type CreatePayoutParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Amount         int64          `json:"amount"`
	ProofObjectKey sql.NullString `json:"proof_object_key"`
	Notes          sql.NullString `json:"notes"`
	UserType       string         `json:"user_type"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, createPayout,
		arg.UserID,
		arg.Amount,
		arg.ProofObjectKey,
		arg.Notes,
		arg.UserType,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.ProofObjectKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UserType,
		&i.Status,
		&i.DanaTransactionID,
		&i.MerchantTransID,
		&i.FailedReason,
	)
	return i, err
}

const getPayoutCountByUserAndDate = `-- name: GetPayoutCountByUserAndDate :one
SELECT COUNT(*) FROM payouts
WHERE user_id = $1 AND user_type = $2 AND status != 'FAILED' AND created_at >= $3
`

type GetPayoutCountByUserAndDateParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UserType  string    `json:"user_type"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPayoutCountByUserAndDate(ctx context.Context, arg GetPayoutCountByUserAndDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPayoutCountByUserAndDate, arg.UserID, arg.UserType, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPayoutByUser = `-- name: GetTotalPayoutByUser :one
SELECT COALESCE(SUM(amount), 0)::bigint as total_paid
FROM payouts
WHERE user_id = $1 AND user_type = $2 AND status != 'FAILED'
`

type GetTotalPayoutByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserType string    `json:"user_type"`
}

func (q *Queries) GetTotalPayoutByUser(ctx context.Context, arg GetTotalPayoutByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPayoutByUser, arg.UserID, arg.UserType)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}

const listAllPayouts = `-- name: ListAllPayouts :many
SELECT p.id, p.user_id, p.amount, p.proof_object_key, p.notes, p.created_at, p.user_type, p.status, p.dana_transaction_id, p.merchant_trans_id, p.failed_reason, COALESCE(r.name, m.name, 'Unknown') as user_name
FROM payouts p
LEFT JOIN resellers r ON p.user_id = r.id AND p.user_type = 'RESELLER'
LEFT JOIN members m ON p.user_id = m.id AND p.user_type = 'MEMBER'
ORDER BY p.created_at DESC
`

type ListAllPayoutsRow struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Amount            int64          `json:"amount"`
	ProofObjectKey    sql.NullString `json:"proof_object_key"`
	Notes             sql.NullString `json:"notes"`
	CreatedAt         time.Time      `json:"created_at"`
	UserType          string         `json:"user_type"`
	Status            string         `json:"status"`
	DanaTransactionID sql.NullString `json:"dana_transaction_id"`
	MerchantTransID   sql.NullString `json:"merchant_trans_id"`
	FailedReason      sql.NullString `json:"failed_reason"`
	UserName          string         `json:"user_name"`
}

func (q *Queries) ListAllPayouts(ctx context.Context) ([]ListAllPayoutsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPayoutsRow
	for rows.Next() {
		var i ListAllPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.ProofObjectKey,
			&i.Notes,
			&i.CreatedAt,
			&i.UserType,
			&i.Status,
			&i.DanaTransactionID,
			&i.MerchantTransID,
			&i.FailedReason,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByUser = `-- name: ListPayoutsByUser :many
SELECT id, user_id, amount, proof_object_key, notes, created_at, user_type, status, dana_transaction_id, merchant_trans_id, failed_reason FROM payouts
WHERE user_id = $1 AND user_type = $2
ORDER BY created_at DESC
`

type ListPayoutsByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserType string    `json:"user_type"`
}

func (q *Queries) ListPayoutsByUser(ctx context.Context, arg ListPayoutsByUserParams) ([]Payout, error) {
	rows, err := q.db.QueryContext(ctx, listPayoutsByUser, arg.UserID, arg.UserType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.ProofObjectKey,
			&i.Notes,
			&i.CreatedAt,
			&i.UserType,
			&i.Status,
			&i.DanaTransactionID,
			&i.MerchantTransID,
			&i.FailedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
