// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payouts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
    reseller_id, amount, proof_object_key, notes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, reseller_id, amount, proof_object_key, notes, created_at
`

type CreatePayoutParams struct {
	ResellerID     uuid.UUID      `json:"reseller_id"`
	Amount         int64          `json:"amount"`
	ProofObjectKey string         `json:"proof_object_key"`
	Notes          sql.NullString `json:"notes"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, createPayout,
		arg.ResellerID,
		arg.Amount,
		arg.ProofObjectKey,
		arg.Notes,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.ResellerID,
		&i.Amount,
		&i.ProofObjectKey,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalPayoutByReseller = `-- name: GetTotalPayoutByReseller :one
SELECT COALESCE(SUM(amount), 0)::bigint as total_paid
FROM payouts
WHERE reseller_id = $1
`

func (q *Queries) GetTotalPayoutByReseller(ctx context.Context, resellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPayoutByReseller, resellerID)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}

const listAllPayouts = `-- name: ListAllPayouts :many
SELECT p.id, p.reseller_id, p.amount, p.proof_object_key, p.notes, p.created_at, u.name as reseller_name
FROM payouts p
JOIN users u ON p.reseller_id = u.id
ORDER BY p.created_at DESC
`

type ListAllPayoutsRow struct {
	ID             uuid.UUID      `json:"id"`
	ResellerID     uuid.UUID      `json:"reseller_id"`
	Amount         int64          `json:"amount"`
	ProofObjectKey string         `json:"proof_object_key"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      time.Time      `json:"created_at"`
	ResellerName   string         `json:"reseller_name"`
}

func (q *Queries) ListAllPayouts(ctx context.Context) ([]ListAllPayoutsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPayoutsRow
	for rows.Next() {
		var i ListAllPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResellerID,
			&i.Amount,
			&i.ProofObjectKey,
			&i.Notes,
			&i.CreatedAt,
			&i.ResellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByReseller = `-- name: ListPayoutsByReseller :many
SELECT id, reseller_id, amount, proof_object_key, notes, created_at FROM payouts
WHERE reseller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPayoutsByReseller(ctx context.Context, resellerID uuid.UUID) ([]Payout, error) {
	rows, err := q.db.QueryContext(ctx, listPayoutsByReseller, resellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.ResellerID,
			&i.Amount,
			&i.ProofObjectKey,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
