// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const adminListProducts = `-- name: AdminListProducts :many
SELECT 
    p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM products p
ORDER BY 
    CASE WHEN p.stock > 0 THEN 0 ELSE 1 END ASC,  -- Products with stock first
    p.created_at DESC                              -- Then by newest first
LIMIT $1 OFFSET $2
`

type AdminListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListProductsRow struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
	ThumbnailUrl     string         `json:"thumbnail_url"`
}

func (q *Queries) AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]AdminListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListProductsRow
	for rows.Next() {
		var i AdminListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionAmount,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.Village,
			&i.Stock,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountAllProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name, parent_id
) VALUES (
    $1, $2
)
RETURNING id, name, parent_id, created_at
`

type CreateCategoryParams struct {
	Name     string        `json:"name"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, title, description, price, commission_amount, status, created_by, 
    location_name, latitude, longitude, province, regency, district, village, stock
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, category_id, title, description, price, status, created_by, created_at, updated_at, commission_amount, location_name, latitude, longitude, province, regency, district, village, stock
`

type CreateProductParams struct {
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	CommissionAmount int64          `json:"commission_amount"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.CommissionAmount,
		arg.Status,
		arg.CreatedBy,
		arg.LocationName,
		arg.Latitude,
		arg.Longitude,
		arg.Province,
		arg.Regency,
		arg.District,
		arg.Village,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionAmount,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.Village,
		&i.Stock,
	)
	return i, err
}

const createProductAsset = `-- name: CreateProductAsset :one
INSERT INTO product_assets (
    product_id, asset_type, object_key
) VALUES (
    $1, $2, $3
)
RETURNING id, product_id, asset_type, object_key, created_at
`

type CreateProductAssetParams struct {
	ProductID uuid.UUID `json:"product_id"`
	AssetType AssetType `json:"asset_type"`
	ObjectKey string    `json:"object_key"`
}

func (q *Queries) CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error) {
	row := q.db.QueryRowContext(ctx, createProductAsset, arg.ProductID, arg.AssetType, arg.ObjectKey)
	var i ProductAsset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AssetType,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const createProductClick = `-- name: CreateProductClick :one
INSERT INTO product_clicks (
    product_id, reseller_id, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, product_id, reseller_id, ip_address, user_agent, clicked_at
`

type CreateProductClickParams struct {
	ProductID  uuid.UUID      `json:"product_id"`
	ResellerID uuid.UUID      `json:"reseller_id"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
}

func (q *Queries) CreateProductClick(ctx context.Context, arg CreateProductClickParams) (ProductClick, error) {
	row := q.db.QueryRowContext(ctx, createProductClick,
		arg.ProductID,
		arg.ResellerID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ProductClick
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ResellerID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ClickedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const deleteProductAsset = `-- name: DeleteProductAsset :exec
DELETE FROM product_assets WHERE id = $1
`

func (q *Queries) DeleteProductAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductAsset, id)
	return err
}

const deleteProductAssets = `-- name: DeleteProductAssets :exec
DELETE FROM product_assets WHERE product_id = $1
`

func (q *Queries) DeleteProductAssets(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductAssets, productID)
	return err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    (SELECT COUNT(*) FROM products) as total_products,
    (SELECT COUNT(*) FROM users WHERE role = 'RESELLER') as total_resellers,
    (SELECT COUNT(*) FROM product_clicks) as total_clicks,
    (SELECT COUNT(*) FROM product_verifications) as total_verifications
`

type GetDashboardStatsRow struct {
	TotalProducts      int64 `json:"total_products"`
	TotalResellers     int64 `json:"total_resellers"`
	TotalClicks        int64 `json:"total_clicks"`
	TotalVerifications int64 `json:"total_verifications"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalResellers,
		&i.TotalClicks,
		&i.TotalVerifications,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, category_id, title, description, price, status, created_by, created_at, updated_at, commission_amount, location_name, latitude, longitude, province, regency, district, village, stock FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionAmount,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.Village,
		&i.Stock,
	)
	return i, err
}

const getProductAssets = `-- name: GetProductAssets :many
SELECT id, product_id, asset_type, object_key, created_at FROM product_assets
WHERE product_id = $1
`

func (q *Queries) GetProductAssets(ctx context.Context, productID uuid.UUID) ([]ProductAsset, error) {
	rows, err := q.db.QueryContext(ctx, getProductAssets, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAsset
	for rows.Next() {
		var i ProductAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AssetType,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductClickStats = `-- name: GetProductClickStats :many
SELECT clicked_at::date as click_date, count(*) as click_count
FROM product_clicks
WHERE product_id = $1
GROUP BY click_date
ORDER BY click_date DESC
`

type GetProductClickStatsRow struct {
	ClickDate  time.Time `json:"click_date"`
	ClickCount int64     `json:"click_count"`
}

func (q *Queries) GetProductClickStats(ctx context.Context, productID uuid.UUID) ([]GetProductClickStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductClickStats, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductClickStatsRow
	for rows.Next() {
		var i GetProductClickStatsRow
		if err := rows.Scan(&i.ClickDate, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithSeller = `-- name: GetProductWithSeller :one
SELECT p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock, 
       COALESCE(u.phone, '')::text as seller_phone, 
       COALESCE(u.name, 'Unknown')::text as seller_name
FROM products p
LEFT JOIN users u ON p.created_by = u.id
WHERE p.id = $1 LIMIT 1
`

type GetProductWithSellerRow struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
	SellerPhone      string         `json:"seller_phone"`
	SellerName       string         `json:"seller_name"`
}

func (q *Queries) GetProductWithSeller(ctx context.Context, id uuid.UUID) (GetProductWithSellerRow, error) {
	row := q.db.QueryRowContext(ctx, getProductWithSeller, id)
	var i GetProductWithSellerRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionAmount,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.Village,
		&i.Stock,
		&i.SellerPhone,
		&i.SellerName,
	)
	return i, err
}

const getResellerClickCount = `-- name: GetResellerClickCount :one
SELECT COUNT(*) FROM product_clicks WHERE reseller_id = $1
`

func (q *Queries) GetResellerClickCount(ctx context.Context, resellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getResellerClickCount, resellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, created_at FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT 
    p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM products p
WHERE 
    (p.status = 'ACTIVE' OR (p.status = 'SOLD' AND p.updated_at >= CURRENT_TIMESTAMP - INTERVAL '1 month')) AND
    ($3::text = '' OR p.location_name ILIKE '%' || $3 || '%')
ORDER BY 
    CASE WHEN p.status = 'ACTIVE' THEN 0 ELSE 1 END ASC,
    p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
}

type ListProductsRow struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
	ThumbnailUrl     string         `json:"thumbnail_url"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionAmount,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.Village,
			&i.Stock,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT 
    p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM products p
WHERE 
    (p.category_id = $1) AND
    ((p.status = 'ACTIVE') OR (p.status = 'SOLD' AND p.updated_at >= CURRENT_TIMESTAMP - INTERVAL '1 month')) AND
    ($4::text = '' OR p.location_name ILIKE '%' || $4 || '%')
ORDER BY 
    CASE WHEN p.status = 'ACTIVE' THEN 0 ELSE 1 END ASC,
    p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
	Column4    string    `json:"column_4"`
}

type ListProductsByCategoryRow struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
	ThumbnailUrl     string         `json:"thumbnail_url"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionAmount,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.Village,
			&i.Stock,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT 
    p.id, p.category_id, p.title, p.description, p.price, p.status, p.created_by, p.created_at, p.updated_at, p.commission_amount, p.location_name, p.latitude, p.longitude, p.province, p.regency, p.district, p.village, p.stock,
    COALESCE((SELECT object_key FROM product_assets a WHERE a.product_id = p.id AND a.asset_type::text ILIKE 'image' LIMIT 1), '')::text as thumbnail_url
FROM products p
WHERE 
    ((p.status = 'ACTIVE') OR (p.status = 'SOLD' AND p.updated_at >= CURRENT_TIMESTAMP - INTERVAL '1 month')) AND
    (p.title ILIKE '%' || $1 || '%' OR p.description ILIKE '%' || $1 || '%') AND
    ($4::text = '' OR p.location_name ILIKE '%' || $4 || '%')
ORDER BY 
    CASE WHEN p.status = 'ACTIVE' THEN 0 ELSE 1 END ASC,
    p.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
	Column4 string         `json:"column_4"`
}

type SearchProductsRow struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	Status           ProductStatus  `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	CommissionAmount int64          `json:"commission_amount"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
	ThumbnailUrl     string         `json:"thumbnail_url"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionAmount,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.Village,
			&i.Stock,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2, title = $3, description = $4, price = $5, commission_amount = $6, status = $7, updated_at = CURRENT_TIMESTAMP,
    location_name = $8, latitude = $9, longitude = $10,
    province = $11, regency = $12, district = $13, village = $14, stock = $15
WHERE id = $1
RETURNING id, category_id, title, description, price, status, created_by, created_at, updated_at, commission_amount, location_name, latitude, longitude, province, regency, district, village, stock
`

type UpdateProductParams struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Price            int64          `json:"price"`
	CommissionAmount int64          `json:"commission_amount"`
	Status           ProductStatus  `json:"status"`
	LocationName     sql.NullString `json:"location_name"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Province         sql.NullString `json:"province"`
	Regency          sql.NullString `json:"regency"`
	District         sql.NullString `json:"district"`
	Village          sql.NullString `json:"village"`
	Stock            int32          `json:"stock"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.CommissionAmount,
		arg.Status,
		arg.LocationName,
		arg.Latitude,
		arg.Longitude,
		arg.Province,
		arg.Regency,
		arg.District,
		arg.Village,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionAmount,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.Village,
		&i.Stock,
	)
	return i, err
}
