// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]AdminListProductsRow, error)
	CountAllProducts(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (ProductLead, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error)
	CreateProductClick(ctx context.Context, arg CreateProductClickParams) (ProductClick, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductAsset(ctx context.Context, id uuid.UUID) error
	DeleteProductAssets(ctx context.Context, productID uuid.UUID) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetCommissionsByReseller(ctx context.Context, resellerID uuid.UUID) ([]Commission, error)
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetLastResellerReferralCode(ctx context.Context) (sql.NullString, error)
	GetLeadsByProduct(ctx context.Context, productID uuid.UUID) ([]GetLeadsByProductRow, error)
	GetLeadsByReseller(ctx context.Context, resellerID uuid.UUID) ([]ProductLead, error)
	GetPendingCommission(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductAssets(ctx context.Context, productID uuid.UUID) ([]ProductAsset, error)
	GetProductClickStats(ctx context.Context, productID uuid.UUID) ([]GetProductClickStatsRow, error)
	GetProductWithSeller(ctx context.Context, id uuid.UUID) (GetProductWithSellerRow, error)
	GetRecentLeads(ctx context.Context, limit int32) ([]GetRecentLeadsRow, error)
	GetResellerByCode(ctx context.Context, referralCode sql.NullString) (User, error)
	GetResellerClickCount(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetResellerCommissions(ctx context.Context, resellerID uuid.UUID) ([]GetResellerCommissionsRow, error)
	GetResellerRecentActivities(ctx context.Context, arg GetResellerRecentActivitiesParams) ([]GetResellerRecentActivitiesRow, error)
	GetResellerRecentLeads(ctx context.Context, arg GetResellerRecentLeadsParams) ([]GetResellerRecentLeadsRow, error)
	GetResellerStats(ctx context.Context, resellerID uuid.UUID) (GetResellerStatsRow, error)
	GetTotalCommission(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetTotalCommissionAll(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetTotalPayoutByReseller(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	ListAdmins(ctx context.Context) ([]Admin, error)
	ListAllPayouts(ctx context.Context) ([]ListAllPayoutsRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListPayoutsByReseller(ctx context.Context, resellerID uuid.UUID) ([]Payout, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error)
	ListResellers(ctx context.Context) ([]User, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
