// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddMartClientFavorite(ctx context.Context, arg AddMartClientFavoriteParams) error
	AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]AdminListProductsRow, error)
	// Check if referral code exists in members OR resellers table
	CheckReferralCodeExists(ctx context.Context, referralCode string) (CheckReferralCodeExistsRow, error)
	CheckReferralCommissionExists(ctx context.Context, arg CheckReferralCommissionExistsParams) (bool, error)
	CountAllProducts(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (ProductLead, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error)
	CreateProductClick(ctx context.Context, arg CreateProductClickParams) (ProductClick, error)
	CreateRegistrationPayment(ctx context.Context, arg CreateRegistrationPaymentParams) (RegistrationPayment, error)
	CreateReseller(ctx context.Context, arg CreateResellerParams) (Reseller, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeviceToken(ctx context.Context, token string) error
	DeleteMember(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductAsset(ctx context.Context, id uuid.UUID) error
	DeleteProductAssets(ctx context.Context, productID uuid.UUID) error
	DeleteReseller(ctx context.Context, id uuid.UUID) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetCommissionLeaderboard(ctx context.Context) ([]GetCommissionLeaderboardRow, error)
	GetCommissionsByUser(ctx context.Context, arg GetCommissionsByUserParams) ([]Commission, error)
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetDeviceTokensByRoles(ctx context.Context, dollar_1 []string) ([]DeviceToken, error)
	GetDeviceTokensByUserIdAndRole(ctx context.Context, arg GetDeviceTokensByUserIdAndRoleParams) ([]DeviceToken, error)
	GetDeviceTokensByUserIdsAndRole(ctx context.Context, arg GetDeviceTokensByUserIdsAndRoleParams) ([]DeviceToken, error)
	GetLastResellerReferralCode(ctx context.Context) (sql.NullString, error)
	GetLeadsByProduct(ctx context.Context, productID uuid.UUID) ([]GetLeadsByProductRow, error)
	GetLeadsByReseller(ctx context.Context, resellerID uuid.NullUUID) ([]ProductLead, error)
	GetMartClientByID(ctx context.Context, id uuid.UUID) (MartClient, error)
	GetMartClientFavoriteExists(ctx context.Context, arg GetMartClientFavoriteExistsParams) (bool, error)
	GetMember(ctx context.Context, id uuid.UUID) (Member, error)
	GetMemberByPhone(ctx context.Context, phone string) (Member, error)
	GetMemberByReferralCode(ctx context.Context, referralCode string) (Member, error)
	GetMemberByUsername(ctx context.Context, username sql.NullString) (Member, error)
	GetMemberRecentActivities(ctx context.Context, arg GetMemberRecentActivitiesParams) ([]GetMemberRecentActivitiesRow, error)
	GetMemberStats(ctx context.Context, memberID uuid.UUID) (GetMemberStatsRow, error)
	GetMemberTeamStats(ctx context.Context, memberID uuid.NullUUID) (GetMemberTeamStatsRow, error)
	GetPayoutCountByUserAndDate(ctx context.Context, arg GetPayoutCountByUserAndDateParams) (int64, error)
	GetPendingCommission(ctx context.Context, arg GetPendingCommissionParams) (int64, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductAsset(ctx context.Context, id uuid.UUID) (ProductAsset, error)
	GetProductAssets(ctx context.Context, productID uuid.UUID) ([]ProductAsset, error)
	GetProductClickStats(ctx context.Context, productID uuid.UUID) ([]GetProductClickStatsRow, error)
	GetProductWithSeller(ctx context.Context, id uuid.UUID) (GetProductWithSellerRow, error)
	GetRecentLeads(ctx context.Context, limit int32) ([]GetRecentLeadsRow, error)
	GetRegistrationPaymentByInvoice(ctx context.Context, invoiceNumber string) (RegistrationPayment, error)
	GetRegistrationPaymentByUserID(ctx context.Context, userID uuid.UUID) (RegistrationPayment, error)
	GetReseller(ctx context.Context, id uuid.UUID) (GetResellerRow, error)
	GetResellerByCode(ctx context.Context, referralCode sql.NullString) (User, error)
	GetResellerByPhone(ctx context.Context, phone string) (Reseller, error)
	GetResellerByReferralCode(ctx context.Context, referralCode string) (Reseller, error)
	GetResellerByUsername(ctx context.Context, username sql.NullString) (Reseller, error)
	GetResellerClickCount(ctx context.Context, resellerID uuid.UUID) (int64, error)
	GetResellerRecentActivities(ctx context.Context, arg GetResellerRecentActivitiesParams) ([]GetResellerRecentActivitiesRow, error)
	GetResellerRecentLeads(ctx context.Context, arg GetResellerRecentLeadsParams) ([]GetResellerRecentLeadsRow, error)
	GetResellerStats(ctx context.Context, resellerID uuid.UUID) (GetResellerStatsRow, error)
	GetSystemConfigByKey(ctx context.Context, key string) (SystemConfig, error)
	GetTotalCommission(ctx context.Context, arg GetTotalCommissionParams) (int64, error)
	GetTotalCommissionAll(ctx context.Context, arg GetTotalCommissionAllParams) (int64, error)
	GetTotalPayoutByUser(ctx context.Context, arg GetTotalPayoutByUserParams) (int64, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserCommissions(ctx context.Context, arg GetUserCommissionsParams) ([]GetUserCommissionsRow, error)
	ListAdmins(ctx context.Context) ([]Admin, error)
	ListAllPayouts(ctx context.Context) ([]ListAllPayoutsRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListMartClientFavorites(ctx context.Context, clientID uuid.UUID) ([]ListMartClientFavoritesRow, error)
	ListMartClients(ctx context.Context, dollar_1 string) ([]MartClient, error)
	ListMembers(ctx context.Context) ([]Member, error)
	ListPayoutsByUser(ctx context.Context, arg ListPayoutsByUserParams) ([]Payout, error)
	ListPendingMembers(ctx context.Context) ([]Member, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error)
	ListResellers(ctx context.Context) ([]User, error)
	ListResellersByMember(ctx context.Context, memberID uuid.NullUUID) ([]Reseller, error)
	ListResellersTable(ctx context.Context) ([]ListResellersTableRow, error)
	ListSystemConfigs(ctx context.Context) ([]SystemConfig, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkMemberPhoneVerified(ctx context.Context, id uuid.UUID) (sql.NullTime, error)
	MarkResellerPhoneVerified(ctx context.Context, id uuid.UUID) (sql.NullTime, error)
	RemoveMartClientFavorite(ctx context.Context, arg RemoveMartClientFavoriteParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	TrackMemberShare(ctx context.Context, arg TrackMemberShareParams) error
	TrackResellerShare(ctx context.Context, arg TrackResellerShareParams) error
	UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error
	UpdateMartClientProfile(ctx context.Context, arg UpdateMartClientProfileParams) (MartClient, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateMemberDanaPhone(ctx context.Context, arg UpdateMemberDanaPhoneParams) (Member, error)
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) (Member, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (Member, error)
	UpdatePayoutDanaStatus(ctx context.Context, arg UpdatePayoutDanaStatusParams) (Payout, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateRegistrationPaymentStatus(ctx context.Context, arg UpdateRegistrationPaymentStatusParams) (RegistrationPayment, error)
	UpdateReseller(ctx context.Context, arg UpdateResellerParams) (Reseller, error)
	UpdateResellerDanaPhone(ctx context.Context, arg UpdateResellerDanaPhoneParams) (Reseller, error)
	UpdateResellerProfile(ctx context.Context, arg UpdateResellerProfileParams) (Reseller, error)
	UpdateResellerStatus(ctx context.Context, arg UpdateResellerStatusParams) (Reseller, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	UpsertMartClientFromGoogle(ctx context.Context, arg UpsertMartClientFromGoogleParams) (MartClient, error)
	UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error)
}

var _ Querier = (*Queries)(nil)
