// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resellers.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReseller = `-- name: CreateReseller :one
INSERT INTO resellers (
    member_id, name, phone, email, password_hash, referral_code, status, username, nik, profile_image, ktp_image
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type CreateResellerParams struct {
	MemberID     uuid.NullUUID  `json:"member_id"`
	Name         string         `json:"name"`
	Phone        string         `json:"phone"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	ReferralCode string         `json:"referral_code"`
	Status       UserStatus     `json:"status"`
	Username     sql.NullString `json:"username"`
	Nik          sql.NullString `json:"nik"`
	ProfileImage sql.NullString `json:"profile_image"`
	KtpImage     sql.NullString `json:"ktp_image"`
}

func (q *Queries) CreateReseller(ctx context.Context, arg CreateResellerParams) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, createReseller,
		arg.MemberID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.ReferralCode,
		arg.Status,
		arg.Username,
		arg.Nik,
		arg.ProfileImage,
		arg.KtpImage,
	)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const deleteReseller = `-- name: DeleteReseller :exec
DELETE FROM resellers WHERE id = $1
`

func (q *Queries) DeleteReseller(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReseller, id)
	return err
}

const getReseller = `-- name: GetReseller :one
SELECT r.id, r.member_id, r.name, r.phone, r.email, r.password_hash, r.referral_code, r.status, r.created_at, r.updated_at, r.username, r.nik, r.profile_image, r.ktp_image, r.bio, r.phone_verified_at, r.dana_phone, m.name as member_name
FROM resellers r
LEFT JOIN members m ON r.member_id = m.id
WHERE r.id = $1 LIMIT 1
`

type GetResellerRow struct {
	ID              uuid.UUID      `json:"id"`
	MemberID        uuid.NullUUID  `json:"member_id"`
	Name            string         `json:"name"`
	Phone           string         `json:"phone"`
	Email           sql.NullString `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	ReferralCode    string         `json:"referral_code"`
	Status          UserStatus     `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Username        sql.NullString `json:"username"`
	Nik             sql.NullString `json:"nik"`
	ProfileImage    sql.NullString `json:"profile_image"`
	KtpImage        sql.NullString `json:"ktp_image"`
	Bio             sql.NullString `json:"bio"`
	PhoneVerifiedAt sql.NullTime   `json:"phone_verified_at"`
	DanaPhone       sql.NullString `json:"dana_phone"`
	MemberName      sql.NullString `json:"member_name"`
}

func (q *Queries) GetReseller(ctx context.Context, id uuid.UUID) (GetResellerRow, error) {
	row := q.db.QueryRowContext(ctx, getReseller, id)
	var i GetResellerRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
		&i.MemberName,
	)
	return i, err
}

const getResellerByPhone = `-- name: GetResellerByPhone :one
SELECT id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM resellers
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetResellerByPhone(ctx context.Context, phone string) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, getResellerByPhone, phone)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const getResellerByReferralCode = `-- name: GetResellerByReferralCode :one
SELECT id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM resellers
WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetResellerByReferralCode(ctx context.Context, referralCode string) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, getResellerByReferralCode, referralCode)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const getResellerByUsername = `-- name: GetResellerByUsername :one
SELECT id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM resellers
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetResellerByUsername(ctx context.Context, username sql.NullString) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, getResellerByUsername, username)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const listResellersByMember = `-- name: ListResellersByMember :many
SELECT id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone FROM resellers
WHERE member_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResellersByMember(ctx context.Context, memberID uuid.NullUUID) ([]Reseller, error) {
	rows, err := q.db.QueryContext(ctx, listResellersByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reseller
	for rows.Next() {
		var i Reseller
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Nik,
			&i.ProfileImage,
			&i.KtpImage,
			&i.Bio,
			&i.PhoneVerifiedAt,
			&i.DanaPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResellersTable = `-- name: ListResellersTable :many
SELECT r.id, r.member_id, r.name, r.phone, r.email, r.password_hash, r.referral_code, r.status, r.created_at, r.updated_at, r.username, r.nik, r.profile_image, r.ktp_image, r.bio, r.phone_verified_at, r.dana_phone, m.name as member_name
FROM resellers r
LEFT JOIN members m ON r.member_id = m.id
ORDER BY r.created_at DESC
`

type ListResellersTableRow struct {
	ID              uuid.UUID      `json:"id"`
	MemberID        uuid.NullUUID  `json:"member_id"`
	Name            string         `json:"name"`
	Phone           string         `json:"phone"`
	Email           sql.NullString `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	ReferralCode    string         `json:"referral_code"`
	Status          UserStatus     `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Username        sql.NullString `json:"username"`
	Nik             sql.NullString `json:"nik"`
	ProfileImage    sql.NullString `json:"profile_image"`
	KtpImage        sql.NullString `json:"ktp_image"`
	Bio             sql.NullString `json:"bio"`
	PhoneVerifiedAt sql.NullTime   `json:"phone_verified_at"`
	DanaPhone       sql.NullString `json:"dana_phone"`
	MemberName      sql.NullString `json:"member_name"`
}

func (q *Queries) ListResellersTable(ctx context.Context) ([]ListResellersTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listResellersTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResellersTableRow
	for rows.Next() {
		var i ListResellersTableRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Nik,
			&i.ProfileImage,
			&i.KtpImage,
			&i.Bio,
			&i.PhoneVerifiedAt,
			&i.DanaPhone,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResellerPhoneVerified = `-- name: MarkResellerPhoneVerified :one
UPDATE resellers
SET phone_verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING phone_verified_at
`

func (q *Queries) MarkResellerPhoneVerified(ctx context.Context, id uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, markResellerPhoneVerified, id)
	var phone_verified_at sql.NullTime
	err := row.Scan(&phone_verified_at)
	return phone_verified_at, err
}

const trackResellerShare = `-- name: TrackResellerShare :exec
INSERT INTO product_resellers (product_id, reseller_id, referral_code)
SELECT $1, $2, referral_code FROM resellers WHERE id = $2
ON CONFLICT (product_id, reseller_id) DO NOTHING
`

type TrackResellerShareParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	ResellerID uuid.UUID `json:"reseller_id"`
}

func (q *Queries) TrackResellerShare(ctx context.Context, arg TrackResellerShareParams) error {
	_, err := q.db.ExecContext(ctx, trackResellerShare, arg.ProductID, arg.ResellerID)
	return err
}

const updateReseller = `-- name: UpdateReseller :one
UPDATE resellers
SET member_id = $2, name = $3, phone = $4, email = $5, status = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateResellerParams struct {
	ID       uuid.UUID      `json:"id"`
	MemberID uuid.NullUUID  `json:"member_id"`
	Name     string         `json:"name"`
	Phone    string         `json:"phone"`
	Email    sql.NullString `json:"email"`
	Status   UserStatus     `json:"status"`
}

func (q *Queries) UpdateReseller(ctx context.Context, arg UpdateResellerParams) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, updateReseller,
		arg.ID,
		arg.MemberID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Status,
	)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}

const updateResellerProfile = `-- name: UpdateResellerProfile :one
UPDATE resellers
SET name = $2, email = $3, bio = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, member_id, name, phone, email, password_hash, referral_code, status, created_at, updated_at, username, nik, profile_image, ktp_image, bio, phone_verified_at, dana_phone
`

type UpdateResellerProfileParams struct {
	ID    uuid.UUID      `json:"id"`
	Name  string         `json:"name"`
	Email sql.NullString `json:"email"`
	Bio   sql.NullString `json:"bio"`
}

func (q *Queries) UpdateResellerProfile(ctx context.Context, arg UpdateResellerProfileParams) (Reseller, error) {
	row := q.db.QueryRowContext(ctx, updateResellerProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Bio,
	)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Nik,
		&i.ProfileImage,
		&i.KtpImage,
		&i.Bio,
		&i.PhoneVerifiedAt,
		&i.DanaPhone,
	)
	return i, err
}
