// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_configs.sql

package db

import (
	"context"
	"database/sql"
)

const getSystemConfigByKey = `-- name: GetSystemConfigByKey :one
SELECT key, value, description, created_at, updated_at FROM system_configs
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSystemConfigByKey(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRowContext(ctx, getSystemConfigByKey, key)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemConfigs = `-- name: ListSystemConfigs :many
SELECT key, value, description, created_at, updated_at FROM system_configs
ORDER BY key ASC
`

func (q *Queries) ListSystemConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.QueryContext(ctx, listSystemConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemConfig
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :one
INSERT INTO system_configs (
    key, value, description, updated_at
) VALUES (
    $1, $2, $3, CURRENT_TIMESTAMP
)
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_configs.description),
    updated_at = CURRENT_TIMESTAMP
RETURNING key, value, description, created_at, updated_at
`

type UpsertSystemConfigParams struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertSystemConfig, arg.Key, arg.Value, arg.Description)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
