// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, phone, email, password_hash, role, referral_code
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, phone, email, password_hash, role, referral_code, created_at, updated_at
`

type CreateUserParams struct {
	Name         string         `json:"name"`
	Phone        string         `json:"phone"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         UserRole       `json:"role"`
	ReferralCode sql.NullString `json:"referral_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ReferralCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastResellerReferralCode = `-- name: GetLastResellerReferralCode :one
SELECT referral_code FROM users
WHERE role = 'RESELLER'
  AND referral_code LIKE 'REF-%'
ORDER BY referral_code DESC
LIMIT 1
`

func (q *Queries) GetLastResellerReferralCode(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getLastResellerReferralCode)
	var referral_code sql.NullString
	err := row.Scan(&referral_code)
	return referral_code, err
}

const getResellerByCode = `-- name: GetResellerByCode :one
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetResellerByCode(ctx context.Context, referralCode sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getResellerByCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResellers = `-- name: ListResellers :many
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users
WHERE role = 'RESELLER'
ORDER BY created_at DESC
`

func (q *Queries) ListResellers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listResellers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.ReferralCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, phone, email, password_hash, role, referral_code, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.ReferralCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    name = $1,
    phone = $2,
    email = COALESCE(NULLIF($3::text, ''), email),
    password_hash = COALESCE(NULLIF($4::text, ''), password_hash),
    updated_at = NOW()
WHERE id = $5
RETURNING id, name, phone, email, password_hash, role, referral_code, created_at, updated_at
`

type UpdateUserParams struct {
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
